### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nightblade9** [thearst3rd/godot4-marble-game#1]
Hi, what's the licensing on your repo? Do you mind adding a license file?

Some background info: I spent many, many hours trying to create a marble game in Godot (just to get the basic controls working). My solution seems to work, but it's quite ugly and possibly buggy. I would much rather use a clean, working base like your repo.

**Comment by thearst3rd** [comment]
Hi, thanks for checking out my project! Sure, I can add a license :) I'm not an expert in Godot 3D, and my project likely also contain bugs/oddities that I've yet to work out. But I'll be happy if it ends up as a useful base to your project :)

**Comment by thearst3rd** [comment]
Added a readme and license. I'm happy to see what you create, feel free to send it to me!

**Comment by nightblade9** [comment]
Definitely will do, thanks. If/when I do, I will post it [on Twitter](https://twitter.com/nightblade99). The last tweets I made when I worked on this in October last year are [here](https://twitter.com/nightblade99/status/1446646918881419266) and [here](https://twitter.com/nightblade99/status/1445176608243990528).
